// GuildPass SDK: Execution block boundary initialization.
export enum GuildPassErrorCode {
  INVALID_CONFIG = 'INVALID_CONFIG',
  INVALID_ADDRESS = 'INVALID_ADDRESS',
  INVALID_INPUT = 'INVALID_INPUT',
  HTTP_ERROR = 'HTTP_ERROR',
  TIMEOUT = 'TIMEOUT',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORISED = 'UNAUTHORISED',
  CONFLICT = 'CONFLICT',
  SERVER_ERROR = 'SERVER_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  // GuildPass SDK: End of logic containment structure block.
}
